sudo: required
dist: trusty
language: node_js
node_js:
- '5'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - php5-cli
    - zip
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
before_install:
- npm set progress=false
- npm prune
after_success: npm run prod
env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=development
  - REPO_NAME=$(basename $TRAVIS_REPO_SLUG)
  - PROJECT_NAME=$(./travis/getName.js)
before_deploy:
- cd ..
- zip -r "${REPO_NAME}-${TRAVIS_TAG}.zip" ${PROJECT_NAME}
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api-key:
    secure: T7e3+CUdArmcKdvgqB6p8ntzp3zRoc+kDPqw6HLyUnV6+uX9lNgNUIdr023nnsGSBq0JEzX4fb0fEmZ1V3esqV1uGkK+hYU7pjYhhhHUHSGdqUDrUSSDq5Yhl8h5bdAUnkDSTPlJR3R32kQ9XcRaa8tVewgPudoN+Gq+8t5msp9UC1bwfjh3x2um+z0L+BCVxEEPXNX3jF0Xe4TfZ+Oy6PiBPQ46Dq9C9QstyN6G2m5BAQx5r4bNaJlfOh7vaSLNgmTbL3aYEUdc9mtWAYnYd5hX2ndjBjZSlVHsRJ7+HqX1i/UmV6pcwLuzeEDi3Dp+CdeHO5zOEncKj/JKPI8a3/KubdLFBagwL3Uof2+t1TQTfyYPqmBaK8EaXawRD2P9YGJ4VZMTkTfYtdSuhOsHyKoax10jlt8RzS5Dc60RjVTa6dSU59klwwGXP6jrFCCWkCIN7e8JsAk4MYZy9axK3KoaSrKhavwv9VfFFJoyA/zZM+u0fskkve7fGM6qQPX9DyzefY94y16NzPWvvo2TcmML3xNWlBLmXiZW5wHRTtJPeUzl/y4GkvphPDfthxCXuAuCkxm3RLSAZMb/bdzO0mTpjIgZ18k0IuE+39r2jiRjnr+qwA0kVi4BFlxKpTGvCursbbgZU/g4Z/mQlacvTzVVwB+SmZSW2T+70dPz90Q=
  file_glob: true
  file: "../${REPO_NAME}-${TRAVIS_TAG}.zip"
  on:
    repo: medfreeman/wp-usine
    tags: true
